Web/ViewModels/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Models;

namespace Web.ViewModels
{
    public class CarViewModel
    {
        public Car Car { get; set; }
        public IEnumerable<Brand> Brands { get; set; }
        public IEnumerable<Model> Models { get; set; }
        public IEnumerable<Owner> Owners { get; set; }
        public IEnumerable<Owner> Drivers { get; set; }
    }
}

Web/Controllers/MaintenanceSpecificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Models;
using DataAccessLayer;
using Core.Interfaces;
using Core.Enums;

namespace Web.Controllers
{
    public class MaintenanceSpecificationsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public MaintenanceSpecificationsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: MaintenanceSpecifications
        public async Task<IActionResult> Index(DateTime? dateFilter, StatusEnum? statusFilter, string order, string search)
        {
            ViewData["IdSortParm"] = String.IsNullOrEmpty(order) ? "Id_desc" : "";
            ViewData["DateSortParm"] = order == "Date" ? "Date_desc" : "Date";
            ViewData["LicenseNumberSortParm"] = order == "License" ? "License_desc" : "License";
            ViewData["StatusSortParm"] = order == "Status" ? "Status_desc" : "Status";

            ViewData["DateFilter"] = dateFilter;
            ViewData["StatusFilter"] = statusFilter;
            ViewData["SearchFilter"] = search;
            ViewData["CurrenstOrder"] = order;

            var maintenanceSpecifications = statusFilter == null ? await _unitOfWork.MaintenanceSpecifications.GetAllAsync() 
                                                           : await _unitOfWork.MaintenanceSpecifications.WhereAsync(ms => ms.Car.Status == statusFilter);

            if (dateFilter != null)
            {
                maintenanceSpecifications = maintenanceSpecifications.Where(ms => ms.Date <= dateFilter);
            }

            if (search != null)
            {
                search = search.ToLower();
                maintenanceSpecifications = maintenanceSpecifications.Where(ms => ms.Car.LicenseNumber.ToLower().Contains(search));
            }

            maintenanceSpecifications = order switch
            {
                "Id_desc" => maintenanceSpecifications.OrderByDescending(ms => ms.MaintenanceSpecificationId),
                "Date" => maintenanceSpecifications.OrderBy(ms => ms.Date),
                "Date_desc" => maintenanceSpecifications.OrderByDescending(ms => ms.Date),
                "License_desc" => maintenanceSpecifications.OrderByDescending(ms => ms.Car.LicenseNumber),
                "License" => maintenanceSpecifications.OrderBy(ms => ms.Car.LicenseNumber),
                "Status" => maintenanceSpecifications.OrderBy(ms => ms.Car.Status),
                "Status_desc" => maintenanceSpecifications.OrderByDescending(ms => ms.Car.Status),
                _ => maintenanceSpecifications.OrderBy(ms => ms.MaintenanceSpecificationId),
            };

            maintenanceSpecifications = maintenanceSpecifications.Where(ms => ms.Car.Status != null
                                                                        && ms.Car.Status != StatusEnum.SIGNED_OFF);

            return View(maintenanceSpecifications);
        }

        // GET: MaintenanceSpecifications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenanceSpecification = await _unitOfWork.MaintenanceSpecifications
                .FindAsync((int)id);

            if (maintenanceSpecification == null)
            {
                return NotFound();
            }

            return View(maintenanceSpecification);
        }

        // GET: MaintenanceSpecifications/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MaintenanceSpecifications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("maintenanceSpecificationId,Name")] MaintenanceSpecification maintenanceSpecification)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.MaintenanceSpecifications.Add(maintenanceSpecification);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(maintenanceSpecification);
        }

        // GET: MaintenanceSpecifications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenanceSpecification = await _unitOfWork.MaintenanceSpecifications.FindAsync((int)id);
            if (maintenanceSpecification == null)
            {
                return NotFound();
            }
            return View(maintenanceSpecification);
        }

        // POST: MaintenanceSpecifications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int maintenanceSpecificationId, [Bind("maintenanceSpecificationId,Name")] MaintenanceSpecification maintenanceSpecification)
        {
            if (maintenanceSpecificationId != maintenanceSpecification.MaintenanceSpecificationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.MaintenanceSpecifications.Update(maintenanceSpecification);
                    await _unitOfWork.CompleteAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaintenanceSpecificationExists(maintenanceSpecification.MaintenanceSpecificationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(maintenanceSpecification);
        }

        // GET: MaintenanceSpecifications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maintenanceSpecification = await _unitOfWork.MaintenanceSpecifications
                .FindAsync((int)id);

            if (maintenanceSpecification == null)
            {
                return NotFound();
            }

            return View(maintenanceSpecification);
        }

        // POST: MaintenanceSpecifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int maintenanceSpecificationId)
        {
            var maintenanceSpecification = await _unitOfWork.MaintenanceSpecifications.FindAsync(maintenanceSpecificationId);
            _unitOfWork.MaintenanceSpecifications.Remove(maintenanceSpecification);
            await _unitOfWork.CompleteAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaintenanceSpecificationExists(int id)
        {
            return _unitOfWork.MaintenanceSpecifications.Find(id) != null;
        }
    }
}

Web/Controllers/OwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Models;
using DataAccessLayer;
using Core.Interfaces;
using Core.Enums;

namespace Web.Controllers
{
    public class OwnersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OwnersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Owners
        public async Task<IActionResult> Index(OwnerEnum type, string order, string search)
        {
            ViewData["Type"] = type.ToString();
            ViewData["NameSortParm"] = String.IsNullOrEmpty(order) ? "Name_desc" : "";
            ViewData["CitySortParm"] = order == "City" ? "City_desc" : "City";

            ViewData["SearchFilter"] = search;
            ViewData["CurrenstOrder"] = order;

            var owners = await _unitOfWork.Owners.WhereAsync(o => o.OwnerType == type);

            if (search != null)
            {
                search = search.ToLower();
                owners = owners.Where(c => (c.Name.ToLower().Contains(search)
                                        || c.City.ToLower().Contains(search)));
            }

            owners = order switch
            {
                "Name_desc" => owners.OrderByDescending(c => c.Name),
                "City" => owners.OrderBy(c => c.City).ThenBy(c => c.Street).ThenBy(c => c.HouseNumber),
                "City_desc" => owners.OrderByDescending(c => c.City).ThenBy(c => c.Street).ThenBy(c => c.HouseNumber),
                _ => owners.OrderBy(c => c.Name),
            };

            return View(owners);
        }

        // GET: Owners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var owner = await _unitOfWork.Owners
                .FindAsync((int)id);

            if (owner == null)
            {
                return NotFound();
            }

            return View(owner);
        }

        // GET: Owners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Owners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OwnerId,Name,City,Street,HouseNumber,Zipcode,PhoneNumber,Email,OwnerType")] Owner owner)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Owners.Add(owner);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index), new { type = (int)owner.OwnerType });
            }
            return View(owner);
        }

        // GET: Owners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var owner = await _unitOfWork.Owners.FindAsync((int)id);
            if (owner == null)
            {
                return NotFound();
            }
            return View(owner);
        }

        // POST: Owners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int ownerId, [Bind("OwnerId,Name,City,Street,HouseNumber,Zipcode,PhoneNumber,Email,OwnerType")] Owner owner)
        {
            if (ownerId != owner.OwnerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.Owners.Update(owner);
                    await _unitOfWork.CompleteAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OwnerExists(owner.OwnerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { type = (int)owner.OwnerType });
            }
            return View(owner);
        }

        // GET: Owners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var owner = await _unitOfWork.Owners
                .FindAsync((int)id);

            if (owner == null)
            {
                return NotFound();
            }

            return View(owner);
        }

        // POST: Owners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int ownerId)
        {
            var owner = await _unitOfWork.Owners.FindAsync(ownerId);
            _unitOfWork.Owners.Remove(owner);
            await _unitOfWork.CompleteAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OwnerExists(int id)
        {
            return _unitOfWork.Owners.Find(id) != null;
        }
    }
}

Web/Views/Cars/BackLogIndex.cshtml
@model IEnumerable<Core.Models.Car>

@{
    ViewData["Title"] = "Cars";
}

<h1>BackLog</h1>

<partial name="~/Views/Shared/Partial/_Partial_Index_Search.cshtml" />

<table class="table table-striped table-hover table-sm">
    <thead class="thead-dark">
        <tr class="d-flex">
            <th class="col-2">
                <a class="text-light font-weight-bold" asp-action="Index" asp-route-order="@ViewData["LicenseNumberParm"]">@Html.DisplayNameFor(model => model.LicenseNumber)</a>
            </th>
            <th class="col-2">
                <a class="text-light font-weight-bold" asp-action="Index" asp-route-order="@ViewData["BrandSortParm"]">@Html.DisplayNameFor(model => model.Model.Brand)</a>
            </th>
            <th class="col-2">
                <a class="text-light font-weight-bold" asp-action="Index" asp-route-order="@ViewData["ModelSortParm"]">@Html.DisplayNameFor(model => model.Model)</a>
            </th>
            <th class="col-2">
                <a class="text-light font-weight-bold" asp-action="Index" asp-route-order="@ViewData["StatusSortParm"]">@Html.DisplayNameFor(model => model.Status)</a>
            </th>
            <th class="col-1">
            </th>
            <th class="col-2">
            </th>
            <th class="col-1">
            </th>
        </tr>
    </thead>
    <tbody class="border">
        @foreach (var item in Model)
        {
            <tr class="d-flex">
                <td class="col-2">
                    @Html.ActionLink(item.LicenseNumber, "Details", new { id = item.CarId })
                </td>
                <td class="col-2">
                    @Html.DisplayFor(modelItem => item.Model.Brand.Name)
                </td>
                <td class="col-2">
                    @Html.DisplayFor(modelItem => item.Model.Name)
                </td>
                <td id="@item.CarId-status" class="col-2">
                    @if (item.Status != Core.Enums.StatusEnum.REGISTERED && item.Status != Core.Enums.StatusEnum.SIGNED_OFF)
                    {
                        @Html.ActionLink(item.Status.ToString(), "Details", "MaintenanceSpecifications", new { id = item.MaintenanceSpecifications.FirstOrDefault().MaintenanceSpecificationId }, null)
                    }
                    else if (item.Status == null && item.Status == Core.Enums.StatusEnum.SIGNED_OFF)
                    {
                        @Html.ActionLink(item.Driver.Name, "Details", "Owners", new { id = item.Driver.OwnerId }, null)
                    }
                </td>

                <td class="col-1">
                    @if (item.Status == Core.Enums.StatusEnum.REGISTERED)
                    {
                        <a id="@item.CarId-btn" class="start-btn btn btn-sm btn-success"
                           asp-controller="maintenanceSpecifications"
                           asp-action="Details"
                           asp-route-id="@item.MaintenanceSpecifications.FirstOrDefault().MaintenanceSpecificationId">Start</a>
                    }
                    else if (item.Status == null || item.Status == Core.Enums.StatusEnum.SIGNED_OFF)
                    {
                        @Html.DisplayFor(modelItem => item.Driver.PhoneNumber)
                    }
                </td>
                <td id="@item.CarId-name" class="col-2">
                </td>
                <td id="@item.CarId-phone" class="col-1">
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {

    <script>

        $(document).ready(function () {


            $('.start-btn').click(function () {
                let actionUrl = "Api/CarsApiEndPoint/Maintenance/" + id;

                $.ajax({
                    type: "PUT",
                    url: actionUrl,
                    success: (data) => {
                        console.log('Succes');
                        console.log(data);
                    },
                    error: (data) => {
                        console.log('Failed');
                        console.log(data);
                    }
                });
            });
        });

    </script>
}

Web/Views/Cars/Create.cshtml
@model Core.Models.Car

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-4">
        <h1>Car</h1>
    </div>
    <div class="offset-7 col-1">
        <a class="btn btn-dark" asp-action="Index" asp-route-type="">Back</a>
    </div>
</div>

<form asp-action="Create">
    <div class="navbar navbar-form navbar-expand-sm bg-dark border box-shadow rounded flex-row justify-content-between">
        <div class="col-md-2 navbar-brand text-light"><b>New</b></div>
        <div class=" btn-group non-editable pr-3">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
    <div class="container pt-3 border border-top-0 rounded-bottom">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-row">
            <div class="col-md-4">
                <label asp-for="LicenseNumber" class="control-label"></label>
                <div class="input-group">
                    <input asp-for="LicenseNumber" class="form-control" />
                    <div class="input-group-append"></div>
                </div>
                <span asp-validation-for="LicenseNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-5">
                <label asp-for="Model.Brand" class="control-label"></label>
                <div class="input-group">
                    <select id="brand-select"
                            class="custom-select"
                            asp-for="Model.Brand.BrandId"
                            asp-items="@ViewBag.BrandId">
                    </select>
                    <div class="input-group-append">
                        <button id="new-brand-btn" class="btn btn-success" type="button">New</button>
                    </div>
                </div>
            </div>
            <span asp-validation-for="Model.Brand" class="text-danger"></span>

            <div class="offset-md-1 col-md-5">
                <label asp-for="Model" class="control-label"></label>
                <div class="input-group">
                    <select id="model-select"
                            class="custom-select"
                            asp-for="Model.ModelId"
                            asp-items="@ViewBag.ModelId">
                    </select>
                    <div class="input-group-append">
                        <button id="new-model-btn" class="btn btn-success" type="button">New</button>
                    </div>
                </div>
            </div>
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>

        <div class="form-row mb-3">
            <div class="col-md-4">
                <label asp-for="Owner" class="control-label"></label>
                <div class="input-group">
                    <select id="owner-select"
                            class="custom-select"
                            asp-for="Owner.OwnerId"
                            asp-items="@ViewBag.OwnerId">
                    </select>
                    <div class="input-group-append">
                    </div>
                </div>
            </div>
            <span asp-validation-for="Owner" class="text-danger"></span>

            <div class="offset-md-2 col-md-4">
                <label asp-for="Driver" class="control-label"></label>
                <div class="input-group">
                    <select id="driver-select"
                            class="custom-select "
                            asp-for="Driver.OwnerId"
                            asp-items="@ViewBag.DriverId">
                    </select>
                    <div class="input-group-append">
                    </div>
                </div>
            </div>
            <span asp-validation-for="Driver" class="text-danger"></span>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Cars/Delete.cshtml
@model Core.Models.Car

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LicenseNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LicenseNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CarId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/Views/Cars/Edit.cshtml
 @model Core.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CarId" />
            <div class="form-group">
                <label asp-for="LicenseNumber" class="control-label"></label>
                <input asp-for="LicenseNumber" class="form-control" />
                <span asp-validation-for="LicenseNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control"
                        asp-items="@Html.GetEnumSelectList<Core.Enums.StatusEnum>()"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Cars/Index.cshtml
@model IEnumerable<Core.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Cars</h1>

<form asp-action="Index" method="get">
    <div class="form-row mb-3">
        <div class="col-2">
            <label for="filter">Search</label>
            <div class="input-group no-color">
                <input type="text" class="form-control" id="search" name="search" value="@ViewData["SearchFilter"]" />
            </div>
        </div>

        <div class="col-md-2 ">
            <label class="control-label">Brand</label>
            <div class="input-group">
                <select id="brand-select"
                        name="brandfilter"
                        class="custom-select "
                        asp-for="@ViewData["BrandFilter"]"
                        asp-items="@ViewBag.BrandId">
                    <option value="">All</option>
                </select>
                <div class="input-group-append">
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <label class="control-label">Model</label>
            <div class="input-group">
                <select id="model-select"
                        name="modelfilter"
                        class="custom-select "
                        asp-for="@ViewData["ModelFilter"]">
                    <option value="">All</option>
                </select>
                <div class="input-group-append">
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <label class="control-label">Company</label>
            <div class="input-group">
                <select id="company-select"
                        name="companyfilter"
                        class="custom-select "
                        asp-for="@ViewData["CompanyFilter"]"
                        asp-items="@ViewBag.CompanyId">
                    <option value="">All</option>
                </select>
                <div class="input-group-append">
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <label for="filter">Status</label>
            <div class="input-group no-color">
                <select id="status-select"
                        name="statusfilter"
                        class="custom-select "
                        asp-for="@ViewData["StatusFilter"]"
                        asp-items="@Html.GetEnumSelectList<Core.Enums.StatusEnum>()">
                    <option value="">All</option>
                </select>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-info">Filter</button>
                </div>
            </div>
        </div>

        <div class="col-md-1 mt-auto">
            <a class="btn btn-success" asp-action="Create">New</a>
        </div>

    </div>
</form>

<table class="table table-striped table-hover table-sm">
    <thead class="thead-dark">
        <tr class="d-flex">
            <th class="col-2">
                @Html.DisplayNameFor(model => model.LicenseNumber)
            </th>
            <th class="col-2">
                @Html.DisplayNameFor(model => model.Model.Brand)
            </th>
            <th class="col-2">
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th class="col-2">
                @Html.DisplayNameFor(model => model.Owner)
            </th>
            <th class="col-2">
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th class="col-2">

            </th>
        </tr>
    </thead>
    <tbody class="border">
        @foreach (var item in Model)
        {
            <tr class="d-flex">
                <td class="col-2">
                @Html.ActionLink(item.LicenseNumber, "Details", new { id = item.CarId })
                </td>
                <td class="col-2">
                    @Html.DisplayFor(modelItem => item.Model.Brand.Name)
                </td>
                <td class="col-2">
                    @Html.DisplayFor(modelItem => item.Model.Name)
                </td>
                <td class="col-2">
                    @Html.DisplayFor(modelItem => item.Owner.Name)
                </td>
                <td class="col-2">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td class="col-2">
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {

    <script>
        $(document).ready(function () {

            $('#brand-select').change(getModels);

            function getModels() {
                let actionUrl = "/Api/ModelsApiEndpoint/GetModelByBrand?id=";
                let brandId = $('#brand-select').val();
                let modelSelect = $('#model-select');

                $.post({
                    url: actionUrl + brandId,
                    success: (data) => {
                        modelSelect.empty();
                        modelSelect.append($('<option></option>').val("").html('All'));
                        $.each(data.data, function (i, item) {
                            modelSelect.append($('<option></option>').val(item.modelId).html(item.name));
                        });
                    },
                    error: (data) => {
                        console.log('Failed');
                        console.log(data);
                    }
                });
            }
        });
    </script>
}